In [140]:
## imports
import numpy as np
import pandas as pd
from sklearn import metrics##used to show the accuracy
from sklearn.metrics import confusion_matrix #used to describe performance of classifier
from sklearn.metrics import classification_report##info abouve accuracy, precision and so on...
from sklearn.model_selection import train_test_split## allows us to split the given data 
from sklearn.feature_extraction.text import CountVectorizer##converts text documents to matrix

In [118]:
## our data imported
info = pd.read_excel(r'C:\Users\ASUS\Desktop\python\azeri_news.xlsx',sep='\t',names=['Category','Title','news_article'])

In [119]:
info.head()## first rows from our data 

Category                                              Title  \
0  Maraqlı     Naviforce Sport Saat 2016 ilə zövqlərin ahəngi   
1  Maraqlı  Sinir ,oynaq , sinir bel ağrılarına 3 gündə son !   
2  Maraqlı            Dəyərindən qat-qat aşağı qiymətə Mənzil   
3    İdman  2024 və 2028-ci il olimpiadalarının keçiriləcə...   
4    Dünya                                 Türkiyədə zəlzələ    

                                        news_article  
0  Naviforce Sport Saat 2016 Yapon Mexanizmi Yapo...  
1  ŞOK ! ŞOK ! ŞOK ! Xanımlar və bəylər , bel və ...  
2  Dəyərindən qat-qat Aşağı Qiymətə. Həzi Aslanov...  
3   2028-ci il Yay Olimpiya və Paralimpiya Oyunla...  
4   Türkiyədə daha bir zəlzələ meydana gəlib.   L...

In [120]:
df_x=info["news_article"]+info["Title"]
df_y=info["Category"]


In [121]:
## Now performing the same with TFID vectorizer
from sklearn.feature_extraction.text import TfidfVectorizer
ve = TfidfVectorizer()

In [141]:
ve.vocabulary_
## mapping of terms to idices of features

{'meksika': 96764,
 'sahillərində': 143208,
 'sakit': 143366,
 'okean': 113966,
 'akvatoriyasında': 7458,
 'bir': 25642,
 'birinin': 25753,
 'ardınca': 12077,
 'maqnitudalı': 94819,
 'iki': 72044,
 'zəlzələ': 193342,
 'baş': 22672,
 'verib': 175825,
 'apa': 10933,
 'nın': 112577,
 'nterfaks': 111804,
 'agentliyinə': 6570,
 'istinadən': 75558,
 'verdiyi': 175751,
 'xəbərə': 181639,
 'görə': 60974,
 'ilk': 72354,
 'tapaçula': 160643,
 'şəhərindən': 205278,
 '134': 956,
 'km': 83835,
 'qərbdə': 136564,
 'qeydə': 130285,
 'alınıb': 9131,
 'kincisi': 82816,
 'xuçitan': 181300,
 '150': 1101,
 'şimal': 203519,
 'şərqdə': 205726,
 'dağıntı': 37995,
 'və': 178265,
 'zərərçəkənlər': 193799,
 'barədə': 21107,
 'məlumat': 105934,
 'verilmir': 175911,
 'meksikada': 96765,
 'sentyabrın': 146841,
 'keçən': 82258,
 'gecə': 57682,
 'bal': 20011,
 'gücündə': 62341,
 'təbii': 167621,
 'fəlakət': 56880,
 'nəticəsində': 113195,
 '96': 4764,
 'nəfər': 112738,
 'ölüb': 199419,
 '200': 1675,
 'müxtəlif': 1041

In [123]:
x_train, x_test, y_train, y_test = train_test_split(df_x, df_y, test_size=0.2, random_state=4)

In [124]:
x_train.head()

16880     Meksika sahillərində, Sakit okean akvatoriyas...
18337    Bir həftədir ki, Bakının Nizami rayonu, Heydər...
11170     Türkiyə prezidenti Rəcəb Tayyib Ərdoğan senty...
17714    Qazaxıstanın paytaxtı Astanada Suriya böhranın...
28539     Bakı. Ənvər Məmmədov - Trend: Bu ilin yanvar-...
dtype: object

In [125]:
x_traincv = ve.fit_transform(x_train)

In [142]:
##performing SVM now
from sklearn.svm import SVC


In [143]:
## with kernel = 'RBF' and gamma = 'scale' the accuracy was 82%
## using cache size to speed up the run process as it takes veeery long
clf = SVC(kernel='linear',gamma= 'auto', C=1, cache_size=7000, random_state = 1)

In [144]:
clf.fit(x_traincv,y_train)

SVC(C=1, break_ties=False, cache_size=7000, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto', kernel='linear',
    max_iter=-1, probability=False, random_state=1, shrinking=True, tol=0.001,
    verbose=False)

In [145]:
cv_t = ve.transform(x_test)
SVM_predicted =clf.predict(cv_t)

In [146]:
SVM_predicted

array(['Maraqlı', 'Dünya', 'Maraqlı', ..., 'Siyasət', 'İqtisadiyyat',
       'Dünya'], dtype=object)

In [147]:
print("Accuracy:",metrics.accuracy_score(y_test, SVM_predicted))

Accuracy: 0.8357


In [148]:
print(classification_report(y_test,SVM_predicted))

              precision    recall  f1-score   support

       Dünya       0.80      0.83      0.81      2656
     Maraqlı       0.83      0.78      0.80      3199
  Mədəniyyət       0.80      0.63      0.71       316
     Siyasət       0.85      0.85      0.85      1300
       İdman       0.90      0.96      0.93      1232
İqtisadiyyat       0.86      0.92      0.89      1297

    accuracy                           0.84     10000
   macro avg       0.84      0.83      0.83     10000
weighted avg       0.83      0.84      0.83     10000



In [149]:
confusion_matrix(y_test, SVM_predicted)

array([[2193,  327,    6,   52,   36,   42],
       [ 408, 2496,   16,   89,   84,  106],
       [  15,   83,  200,   12,    2,    4],
       [  79,   54,   16, 1099,   11,   41],
       [  20,   19,    2,    9, 1180,    2],
       [  22,   37,    9,   38,    2, 1189]], dtype=int64)

In [12]:
##importing neural network
##without any hyperparameters the accuracy was only 76 
from sklearn.neural_network import MLPClassifier
mc = MLPClassifier(hidden_layer_sizes=(10,10,10),activation='relu', solver='adam', random_state = 1, max_iter=200)


In [13]:
mc.fit(x_traincv, y_train)


c:\users\asus\appdata\local\programs\python\python37\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
              beta_2=0.999, early_stopping=False, epsilon=1e-08,
              hidden_layer_sizes=(10, 10, 10), learning_rate='constant',
              learning_rate_init=0.001, max_fun=15000, max_iter=200,
              momentum=0.9, n_iter_no_change=10, nesterovs_momentum=True,
              power_t=0.5, random_state=None, shuffle=True, solver='adam',
              tol=0.0001, validation_fraction=0.1, verbose=False,
              warm_start=False)

In [15]:
cv_t = ve.transform(x_test)
NN_prediction1 = mc.predict(cv_t)

In [16]:
NN_prediction1

array(['Maraqlı', 'Dünya', 'Maraqlı', ..., 'Siyasət', 'İqtisadiyyat',
       'Dünya'], dtype='<U12')

In [17]:
print("Accuracy:",metrics.accuracy_score(y_test, NN_prediction1))

Accuracy: 0.791


In [18]:
print(classification_report(y_test,NN_prediction1))

              precision    recall  f1-score   support

       Dünya       0.77      0.78      0.77      2656
     Maraqlı       0.75      0.75      0.75      3199
  Mədəniyyət       0.76      0.63      0.69       316
     Siyasət       0.80      0.81      0.80      1300
       İdman       0.89      0.88      0.89      1232
İqtisadiyyat       0.84      0.84      0.84      1297

    accuracy                           0.79     10000
   macro avg       0.80      0.78      0.79     10000
weighted avg       0.79      0.79      0.79     10000



In [19]:
confusion_matrix(y_test, NN_prediction1)

array([[2073,  425,   11,   77,   35,   35],
       [ 463, 2414,   31,   99,   81,  111],
       [  12,   78,  200,   15,    3,    8],
       [  65,  108,   12, 1051,   12,   52],
       [  49,   79,    2,   14, 1086,    2],
       [  37,  109,    7,   56,    2, 1086]], dtype=int64)

In [133]:
## entropy best 72 accuracy
## gini best 73 accuracy
## gini best spli=40n random staste 1 accuracy 74
##importing Decision Tree Classifier
from sklearn.tree import DecisionTreeClassifier
dtree = DecisionTreeClassifier(class_weight=None, criterion= 'gini', max_depth=None,
max_features=None, max_leaf_nodes=None,splitter='best', min_samples_split=40,random_state = 1)
cv_t = ve.transform(x_test)

In [134]:
dtree.fit(x_traincv, y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=40,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=1, splitter='best')

In [135]:
DTC_prediction = dtree.predict(cv_t)

In [136]:
print("Accuracy:",metrics.accuracy_score(y_test,DTC_prediction))

Accuracy: 0.7366


In [137]:
print(classification_report(y_test,DTC_prediction))

              precision    recall  f1-score   support

       Dünya       0.71      0.77      0.74      2656
     Maraqlı       0.74      0.73      0.73      3199
  Mədəniyyət       0.54      0.39      0.45       316
     Siyasət       0.72      0.71      0.71      1300
       İdman       0.85      0.81      0.83      1232
İqtisadiyyat       0.73      0.72      0.73      1297

    accuracy                           0.74     10000
   macro avg       0.72      0.69      0.70     10000
weighted avg       0.74      0.74      0.74     10000



In [138]:
DTC_prediction

array(['Maraqlı', 'Dünya', 'Maraqlı', ..., 'Siyasət', 'İqtisadiyyat',
       'Dünya'], dtype=object)

In [139]:
confusion_matrix(y_test, DTC_prediction)

array([[2054,  406,   15,   64,   48,   69],
       [ 519, 2323,   48,  120,   76,  113],
       [  25,   76,  122,   40,   13,   40],
       [ 113,  124,   16,  923,   21,  103],
       [  78,   92,    6,   26, 1004,   26],
       [  90,  122,   19,  109,   17,  940]], dtype=int64)